version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/chessButBetter
hooks:
  AfterInstall:
    - location: scripts/install_frontend.sh
      runas: root
    - location: scripts/install_backend.sh
      runas: root
    - location: scripts/copy_secrets.sh
      runas: root
  ApplicationStart:
    - location: scripts/start_frontend.sh
      runas: ec2-user
    - location: scripts/start_backend.sh
      runas: ec2-user