version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/chessButBetter
hooks:
  AfterInstall:
    - location: scripts/install_frontend.sh
    - location: scripts/install_backend.sh
  ApplicationStart:
    - location: scripts/start_frontend.sh
    - location: scripts/start_backend.sh