name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Change to your AWS region

      # Step 3: Deploy your application
      # This example uses AWS CodeDeploy. Adjust according to your deployment service.
      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ChessButBetter \
            --deployment-group-name YourDeploymentGroupName \
            --revision revisionType=GitHub,repository=Fighter077/chessButBetterV2,commitId=${{ github.sha }}